# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: spacebook_development
  username: <%= ENV.fetch("POSTGRE_USER")%>
  password: <%= ENV.fetch("POSTGRE_PASSWORD")%>
  encoding: unicode
  host: <%= ENV.fetch("POSTGRE_HOST")%>
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: spacebook_test
  username: <%= ENV.fetch("POSTGRE_USER")%>
  password: <%= ENV.fetch("POSTGRE_PASSWORD")%>
  encoding: unicode
  host: <%= ENV.fetch("POSTGRE_HOST")%>
  port: 5432
  pool: 5
